"""Step 02 entry point — validate the raw data against its contract.

    make validate         # or: python -m hrai.validation.run

Raw data is validated in ``report`` mode: the violations found here (finding
F6) are the specification for what Step 03 must fix. The report is written to
``docs/validation_report.json`` and rendered into
``docs/validation_report.md``.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime

from hrai.utils.config import project_root
from hrai.utils.io import load_raw
from hrai.utils.logger import get_logger, run_id, setup_logging
from hrai.validation.runner import validate_all
from hrai.validation.schemas import RAW_SCHEMAS

log = get_logger(__name__)


def main(mode: str = "report") -> int:
    setup_logging()
    frames = {name: load_raw(name) for name in RAW_SCHEMAS}
    reports = validate_all(frames, RAW_SCHEMAS, mode=mode)

    payload = {
        "generated_at": datetime.now(UTC).isoformat(),
        "run_id": run_id(),
        "mode": mode,
        "stage": "raw",
        "datasets": {name: r.to_dict() for name, r in reports.items()},
    }
    root = project_root()
    (root / "docs" / "validation_report.json").write_text(
        json.dumps(payload, indent=2), encoding="utf-8"
    )

    lines = [
        "# Validation Report — raw data",
        "",
        "> Generated by `make validate` (Step 02). Violations here are expected: they are "
        "the defects finding F6 documents, and they define what Step 03 must fix.",
        "",
        f"- Generated: `{payload['generated_at']}`  ·  Mode: `{mode}`",
        "",
        "| Dataset | Rows | Result | Violations |",
        "|---|---|---|---|",
    ]
    for name, r in reports.items():
        lines.append(
            f"| `{name}` | {r.rows:,} | {'PASS' if r.passed else 'FAIL'} | {r.failure_count:,} |"
        )
    lines.append("")
    for name, r in reports.items():
        if r.passed:
            continue
        lines += [
            f"## `{name}`",
            "",
            "| Check | Scope | Column | Rows affected | Example |",
            "|---|---|---|---|---|",
        ]
        for f in r.failures:
            lines.append(
                f"| `{f['check']}` | {f.get('scope','column')} | `{f['column'] or '—'}` "
                f"| {f['count']:,} | `{f['example']}` |"
            )
        lines.append("")
    (root / "docs" / "validation_report.md").write_text("\n".join(lines), encoding="utf-8")

    total = sum(r.failure_count for r in reports.values())
    log.info(
        "step 02 complete",
        extra={
            "datasets": len(reports),
            "passing": sum(r.passed for r in reports.values()),
            "total_violations": total,
        },
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
