"""Step 04 — document how the five tables actually connect.

    python -m hrai.profiling.relationships

Writes `docs/data_relationships.md`: for every pair of tables, the join key,
the cardinality, the referential-integrity result and the reason. The F1
evidence is recorded next to the decision it drove, so the reasoning survives
long after the conversation that produced it.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime

from hrai.utils.config import project_root
from hrai.utils.io import load_processed
from hrai.utils.logger import get_logger, setup_logging

log = get_logger(__name__)

DIAGRAM = """```
  POPULATION A                                  POPULATION B
  employee_attrition (1,470)                    hr_performance_engagement (3,000)
  key:   EmployeeNumber                         key:   Employee ID
  label: Attrition           16.1% Yes          label: Voluntarily Terminated  10.8%
        |                                                     |
        |  X-------- NO EMPLOYEE-LEVEL JOIN (F1) --------X    |
        |                                                     |
        | JobRole (9)                              Title (31) |
        v                                                     v
        +--------->  ROLE -> O*NET SOC CROSSWALK  <-----------+
                     semantic + human-reviewed, 40 roles
                                  |
                                  v
                        occupation_master (1,016 SOC)
                          |                        |
                          v                        v
              essential_skills              software_skills
              TIER 1 foundational           TIER 2 technical
              10 skills, IM 1-5 / LV 1-7    8,751 tools / 134 categories
              910 occupations               923 occupations
```"""


def main() -> int:
    setup_logging()
    root = project_root()

    findings = json.loads((root / "docs" / "findings.json").read_text(encoding="utf-8"))
    f1 = findings["F1_employee_population_identity"]
    integrity = findings["onet_referential_integrity"]

    occ = load_processed("occupation_master")
    ess = load_processed("essential_skills_processed")
    sw = load_processed("software_skills_processed")
    att = load_processed("employee_attrition_processed")
    eng = load_processed("engagement_processed")

    occ_codes = set(occ["soc_code"])
    ess_orphans = len(set(ess["soc_code"]) - occ_codes)
    sw_orphans = len(set(sw["soc_code"]) - occ_codes)

    rows = [
        [
            "`employee_attrition`",
            "`hr_performance_engagement`",
            "`EmployeeNumber` = `Employee ID`",
            "**NONE — forbidden**",
            "n/a",
            f"Coincidental overlap: {f1['shared_key_count']} shared IDs, attributes agree "
            f"{f1.get('mean_agreement_pct')}%. Different companies (F1).",
        ],
        [
            "`employee_attrition`",
            "`occupation_master`",
            "`JobRole` -> `soc_code` via crosswalk",
            "many-to-one",
            "via crosswalk",
            "0 exact title matches (F4); resolved by the semantic crosswalk.",
        ],
        [
            "`hr_performance_engagement`",
            "`occupation_master`",
            "`Title` -> `soc_code` via crosswalk",
            "many-to-one",
            "via crosswalk",
            "0 exact title matches (F4); resolved by the semantic crosswalk.",
        ],
        [
            "`occupation_master`",
            "`essential_skills_processed`",
            "`soc_code`",
            "one-to-many",
            f"{'PASS' if ess_orphans == 0 else f'{ess_orphans} orphans'}",
            f"Tier 1 foundational skills. {integrity['occupations_without_essential_skills']} "
            "occupations have no skills row.",
        ],
        [
            "`occupation_master`",
            "`software_skills_processed`",
            "`soc_code`",
            "one-to-many",
            f"{'PASS' if sw_orphans == 0 else f'{sw_orphans} orphans'}",
            f"Tier 2 technical tools. {integrity['occupations_without_software_skills']} "
            "occupations have no tools row.",
        ],
        [
            "`engagement_processed`",
            "`engagement_events_processed`",
            "`employee_id`",
            "one-to-many",
            "PASS",
            "Employee grain vs event grain (F5): 3,000 employees, 3,150 events.",
        ],
    ]

    lines = [
        "# Data Relationships",
        "",
        "> Generated by `python -m hrai.profiling.relationships` (Step 04).",
        f"> Generated: `{datetime.now(UTC).isoformat()}`",
        "",
        "## Topology",
        "",
        DIAGRAM,
        "",
        "The two employee populations are bridged **by the role/skill ontology, not by "
        "employee identity**. See `docs/adr/001-two-population-architecture.md`.",
        "",
        "## Every pair of tables",
        "",
        "| Left | Right | Join key | Cardinality | Referential integrity | Why |",
        "|---|---|---|---|---|---|",
    ]
    lines += ["| " + " | ".join(r) + " |" for r in rows]

    lines += [
        "",
        "## The forbidden join, in full",
        "",
        "Build Notes Step 04 states the two employee tables join one-to-one on "
        "`EmployeeID`. Tested before building:",
        "",
        "| Attribute compared | Rows compared | Agree | Agreement |",
        "|---|---|---|---|",
    ]
    for label, detail in f1["attribute_agreement"].items():
        lines.append(
            f"| `{label}` | {detail['compared']:,} | {detail['agree']:,} | "
            f"**{detail['agree_pct']}%** |"
        )
    lines += [
        "",
        f"> {f1['verdict']}",
        "",
        "Enforced by `scripts/check_no_cross_population_join.py` in pre-commit and CI, "
        "and asserted by `tests/unit/test_no_cross_population_join.py`.",
        "",
        "## Population summary",
        "",
        "| Population | Table | Employees | Label | Positive rate |",
        "|---|---|---|---|---|",
        f"| A | `employee_attrition_processed` | {len(att):,} | `attrition_flag` | "
        f"{att['attrition_flag'].mean():.1%} |",
        f"| B | `engagement_processed` | {len(eng):,} | `is_voluntary_exit` | "
        f"{eng['is_voluntary_exit'].mean():.1%} |",
        "",
        "Population B's independent label is what makes cross-population transfer "
        "validation possible: a model trained on A can be scored against B's own "
        "outcomes rather than against an assumption.",
        "",
    ]

    path = root / "docs" / "data_relationships.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    log.info(
        "step 04 complete",
        extra={"document": str(path.relative_to(root)), "pairs_documented": len(rows)},
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
